Codigo/VentasWeb/VentasWeb/Controllers/CompraController.cs
using CapaDatos;
using CapaModelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VentasWeb.Controllers
{
    public class CompraController : Controller
    {
        private static Usuario SesionUsuario;
        // GET: Compra
        public ActionResult Crear()
        {
            SesionUsuario = (Usuario)Session["Usuario"];
            return View();
        }
        // GET: Compra
        public ActionResult Consultar()
        {
            return View();
        }

        public ActionResult Documento(int idcompra = 0) {
            
            Compra oCompra = CD_Compra.Instancia.ObtenerDetalleCompra(idcompra);

            if (oCompra == null) {
                oCompra = new Compra();
            }


            return View(oCompra);
        }


        public JsonResult Obtener(string fechainicio, string fechafin, int idproveedor, int idtienda)
        {
            List<Compra> lista = CD_Compra.Instancia.ObtenerListaCompra(Convert.ToDateTime(fechainicio), Convert.ToDateTime(fechafin), idproveedor, idtienda);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Guardar(string xml)
        {
            xml = xml.Replace("!idusuario¡", SesionUsuario.IdUsuario.ToString());

            bool respuesta  = CD_Compra.Instancia.RegistrarCompra(xml);

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }



    }
}

Codigo/VentasWeb/VentasWeb/Controllers/RolController.cs
using CapaDatos;
using CapaModelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VentasWeb.Controllers
{
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Crear()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Obtener()
        {
            List<Rol> olista = CD_Rol.Instancia.ObtenerRol();
           
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Guardar(Rol objeto)
        {
            bool respuesta = false;

            if (objeto.IdRol == 0)
            {

                respuesta = CD_Rol.Instancia.RegistrarRol(objeto);
            }
            else
            {
                respuesta = CD_Rol.Instancia.ModificarRol(objeto);
            }


            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult Eliminar(int id = 0)
        {
            bool respuesta = CD_Rol.Instancia.EliminarRol(id);

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

    }
}

Codigo/VentasWeb/VentasWeb/Controllers/TiendaController.cs
using CapaDatos;
using CapaModelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VentasWeb.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Crear()
        {
            return View();
        }

        public JsonResult Obtener()
        {
            List<Tienda> lista = CD_Tienda.Instancia.ObtenerTiendas();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
    
        [HttpPost]
        public JsonResult Guardar(Tienda objeto)
        {
            bool respuesta = false;

            if (objeto.IdTienda == 0)
            {

                respuesta = CD_Tienda.Instancia.RegistrarTienda(objeto);
            }
            else
            {
                respuesta = CD_Tienda.Instancia.ModificarTienda(objeto);
            }


            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Eliminar(int id = 0)
        {
            bool respuesta = CD_Tienda.Instancia.EliminarTienda (id);

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

Codigo/VentasWeb/VentasWeb/Controllers/VentaController.cs
using CapaDatos;
using CapaModelo;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VentasWeb.Controllers
{
    public class VentaController : Controller
    {
        private static Usuario SesionUsuario;
        // GET: Venta
        public ActionResult Crear()
        {
            SesionUsuario = (Usuario)Session["Usuario"];
            return View();
        }

        // GET: Venta
        public ActionResult Consultar()
        {
            return View();
        }

        public ActionResult Documento(int IdVenta = 0)
        {

            Venta oVenta = CD_Venta.Instancia.ObtenerDetalleVenta(IdVenta);



            NumberFormatInfo formato = new CultureInfo("es-PE").NumberFormat;
            formato.CurrencyGroupSeparator = ".";


            if (oVenta == null)
                oVenta = new Venta();
            else {

                oVenta.oListaDetalleVenta = (from dv in oVenta.oListaDetalleVenta
                                             select new DetalleVenta()
                                             {
                                                 Cantidad = dv.Cantidad,
                                                 NombreProducto = dv.NombreProducto,
                                                 PrecioUnidad = dv.PrecioUnidad,
                                                 TextoPrecioUnidad = dv.PrecioUnidad.ToString("N", formato), //numero.ToString("C", formato)
                                                 ImporteTotal = dv.ImporteTotal,
                                                 TextoImporteTotal = dv.ImporteTotal.ToString("N", formato)
                                             }).ToList();

                oVenta.TextoImporteRecibido = oVenta.ImporteRecibido.ToString("N", formato);
                oVenta.TextoImporteCambio = oVenta.ImporteCambio.ToString("N", formato);
                oVenta.TextoTotalCosto = oVenta.TotalCosto.ToString("N", formato);
            }
               

            return View(oVenta);
        }


        public JsonResult Obtener(string codigo, string fechainicio, string fechafin, string numerodocumento, string nombres)
        {
            List<Venta> lista = CD_Venta.Instancia.ObtenerListaVenta(codigo, Convert.ToDateTime(fechainicio), Convert.ToDateTime(fechafin), numerodocumento, nombres);


            if (lista == null)
                lista = new List<Venta>();

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult ObtenerUsuario()
        {
            Usuario rptUsuario = CD_Usuario.Instancia.ObtenerDetalleUsuario(SesionUsuario.IdUsuario);
            return Json(rptUsuario, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ObtenerProductoPorTienda(int IdTienda)
        {

            List<ProductoTienda> oListaProductoTienda = CD_ProductoTienda.Instancia.ObtenerProductoTienda();
            oListaProductoTienda = oListaProductoTienda.Where(x => x.oTienda.IdTienda == IdTienda && x.Stock > 0).ToList();


            return Json(new { data = oListaProductoTienda }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ControlarStock(int idproducto, int idtienda, int cantidad, bool restar)
        {
            bool respuesta = CD_ProductoTienda.Instancia.ControlarStock(idproducto, idtienda, cantidad, restar);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Guardar(string xml)
        {
            xml = xml.Replace("!idusuario¡", SesionUsuario.IdUsuario.ToString());
            int Respuesta = 0;
            Respuesta = CD_Venta.Instancia.RegistrarVenta(xml);
            if (Respuesta != 0)
                return Json(new { estado = true, valor = Respuesta.ToString() }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { estado = false, valor = "" }, JsonRequestBehavior.AllowGet);
        }

    }
}

Codigo/VentasWeb/VentasWeb/Views/Shared/_Layout.cshtml
@using VentasWeb.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <title>Inventario Secr. Salud</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/PluginsCSS")
    @RenderSection("estilos", required: false)
</head>
<body>

    <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-info" style="font-weight:bold">
        <a class="navbar-brand" href="#">
            <img src="@Url.Content("~/Imagenes/logo_menu.png")" width="90" height="80" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" name="Home" href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i> Inicio</a>
                </li>
                @Html.ActionLinkAllow()
            </ul>
            <ul class="nav navbar-nav ml-auto">
                
                <li class="nav-item">
                    <a href="@Url.Action("Salir", "Home")" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i>
                        <span>
                            <strong>Salir</strong>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid " style="background-image: url(../Imagenes/fondoPrincipall.jpg); height:90vh">
        @RenderBody()
        <hr />
        <footer>
            <p style="color:white">&copy; @DateTime.Now.Year - Secretaria de Salud - Computos - Para el pana Alejandro</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/PluginsJS")

    <script type="text/javascript">

        $.extend({ MisUrls: { url: {}, urls: function (a) { $.extend($.MisUrls.url, a); } } });

        //CONTROLADOR ROL
        $.MisUrls.urls({ _ObtenerRoles: '@Url.Action("Obtener", "Rol")' });
        $.MisUrls.urls({ _GuardarRol: '@Url.Action("Guardar", "Rol")' });
        $.MisUrls.urls({ _EliminarRol: '@Url.Action("Eliminar", "Rol")' });

        //CONTROLADOR PERMISOS
        $.MisUrls.urls({ _ObtenerPermisos: '@Url.Action("Obtener", "Permisos")' });
        $.MisUrls.urls({ _GuardarPermisos: '@Url.Action("Guardar", "Permisos")' });


        //CONTROLADOR USUARIO
        $.MisUrls.urls({ _ObtenerUsuarios: '@Url.Action("Obtener", "Usuario")' });
        $.MisUrls.urls({ _GuardarUsuario: '@Url.Action("Guardar", "Usuario")' });
        $.MisUrls.urls({ _EliminarUsuario: '@Url.Action("Eliminar", "Usuario")' });

        //CONTROLADOR PROVEEDOR
        $.MisUrls.urls({ _ObtenerProveedores: '@Url.Action("Obtener", "Proveedor")' });
        $.MisUrls.urls({ _GuardarProveedor: '@Url.Action("Guardar", "Proveedor")' });
        $.MisUrls.urls({ _EliminarProveedor: '@Url.Action("Eliminar", "Proveedor")' });

        //CONTROLADOR CATEGORIA
        $.MisUrls.urls({ _ObtenerCategorias: '@Url.Action("Obtener", "Categoria")' });
        $.MisUrls.urls({ _GuardarCategoria: '@Url.Action("Guardar", "Categoria")' });
        $.MisUrls.urls({ _EliminarCategoria: '@Url.Action("Eliminar", "Categoria")' });


         //CONTROLADOR PRODUCTO
        $.MisUrls.urls({ _ObtenerProductos: '@Url.Action("Obtener", "Producto")' });
        $.MisUrls.urls({ _ObtenerProductosPorTienda: '@Url.Action("ObtenerPorTienda", "Producto")' });
        $.MisUrls.urls({ _GuardarProducto: '@Url.Action("Guardar", "Producto")' });
        $.MisUrls.urls({ _EliminarProducto: '@Url.Action("Eliminar", "Producto")' });
        $.MisUrls.urls({ _ObtenerAsignaciones: '@Url.Action("ObtenerAsignaciones", "Producto")' });
        $.MisUrls.urls({ _RegistrarProductoTienda: '@Url.Action("RegistrarProductoTienda", "Producto")' });
        $.MisUrls.urls({ _ModificarProductoTienda: '@Url.Action("ModificarProductoTienda", "Producto")' });
        $.MisUrls.urls({ _EliminarProductoTienda: '@Url.Action("EliminarProductoTienda", "Producto")' });


        //CONTROLADOR TIENDA
        $.MisUrls.urls({ _ObtenerTiendas: '@Url.Action("Obtener", "Tienda")' });
         $.MisUrls.urls({ _GuardarTienda: '@Url.Action("Guardar", "Tienda")' });
        $.MisUrls.urls({ _EliminarTienda: '@Url.Action("Eliminar", "Tienda")' });

        //CONTROLADOR COMPRA
        $.MisUrls.urls({ _ObtenerCompras: '@Url.Action("Obtener", "Compra")' });
        $.MisUrls.urls({ _GuardarCompra: '@Url.Action("Guardar", "Compra")' });
        $.MisUrls.urls({ _DocumentoCompra: '@Url.Action("Documento", "Compra")' });


        //CONTROLADOR VENTA
        $.MisUrls.urls({ _ObtenerUsuario: '@Url.Action("ObtenerUsuario", "Venta")' });
        $.MisUrls.urls({ _ObtenerProductoStockPorTienda: '@Url.Action("ObtenerProductoPorTienda", "Venta")' });
        $.MisUrls.urls({ _ControlarStockProducto: '@Url.Action("ControlarStock", "Venta")' });
        $.MisUrls.urls({ _RegistrarVenta: '@Url.Action("Guardar", "Venta")' });
        $.MisUrls.urls({ _DocumentoVenta: '@Url.Action("Documento", "Venta")' });
        $.MisUrls.urls({ _ObtenerVentas: '@Url.Action("Obtener", "Venta")' });

        //CONTROLADOR REPORTE
        $.MisUrls.urls({ _ObtenerReporteProducto :'@Url.Action("ObtenerProducto", "Reporte")' });
        $.MisUrls.urls({ _ObtenerReporteVenta :'@Url.Action("ObtenerVenta", "Reporte")' });


        //CONTROLADOR CLIENTE
        $.MisUrls.urls({ _ObtenerClientes: '@Url.Action("Obtener", "Cliente")' });
        $.MisUrls.urls({ _GuardarCliente: '@Url.Action("Guardar", "Cliente")' });
        $.MisUrls.urls({ _EliminarCliente: '@Url.Action("Eliminar", "Cliente")' });


        //lenguaje español datatable
        $.MisUrls.urls({ Url_datatable_spanish: '@Url.Content("~/content/plugins/datatables/js/datatable_spanish.json")' });



    </script>
    <script>

        function activarMenu(menuactivo) {

            var ul = $("ul.navbar-nav");
            ul.find("li.nav-item").each(function (i, li) {

                var a;

                if ($(li).find("div.dropdown-menu").length != 0) {

                    var div = $($(li).find("div.dropdown-menu"))
                   
                    div.find("a.dropdown-item").each(function (x, tagA) {
                        if ($(tagA).attr("name") == menuactivo) {
                            
                            $(li).addClass("active");
                            return false;
                        }
                    })
                } else {

                    a = $(li).find("a.nav-link");

                    if ($(a).attr("name") == menuactivo) {
                        $(li).addClass("active");
                        return false;
                    }
                }
            });
        }

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>